configserver: 
  image: anilallewar/basic-config-server
  tag: 0.0.1
  replicaCount: 1

image:
  pullPolicy: IfNotPresent
  
service:
  configserver:
    type: LoadBalancer
    externalPort: 8888
    internalPort: 8888