apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
      - name: {{ .Release.Name }}-mysql
        image: {{ .Values.mysql.image }}:{{ .Values.mysql.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.mysql.internalPort }}
          name: "tcp"
        env:
        - name: MYSQL_DATABASE
          value: {{ .Values.service.mysql.database }}
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.service.mysql.rootPassword }}
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-config-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-config-server
    spec:
      containers:
      - name: {{ .Release.Name }}-config-server
        image: {{ .Values.configserver.image }}:{{ .Values.configserver.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.configserver.internalPort}}
          name: "http"
        command: ["/bin/bash"]
        args: ["-c", 'until nslookup {{ .Release.Name }}-mysql; do echo Waiting for mySql database to start; sleep 5; done; /app/run.sh']