apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app: {{ .Release.Name }}-config-server
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.configserver.internalPort }}
    targetPort: {{ .Values.service.configserver.externalPort }}
  type: {{ .Values.service.configserver.type }}