apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-config-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-config-server
    spec:
      containers:
      - name: {{ .Release.Name }}-config-server
        image: {{ .Values.configserver.image }}:{{ .Values.configserver.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.configserver.internalPort}}
          name: "http"