spring:
  #profiles:
    #active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abhisekknp/microservice-demo1
       # native:
          #search-locations: file:///C:/Falcon/lab/config-repo

# While in development mode, you can configure the config server to pick up configuration files from
# the file system
          
#           uri: file://Users/anilallewar/Documents/Anil Allewar/Trainings/Code Samples/Enterprise Java/Micro Services/sample-config

# Defines the port where the config server is running so that rest of the services can pick up 
# their external configurations
server:
  port: 8888